### ISSUE TITLE
No playlist found in Plex

### ISSUE THREAD

**Issue by arsaboo** [XDGFX/ultrasonics#32]
I am trying to sync my Plex playlists to Spotify. I have connected both the services. But, when I run the applet, I see that no playlists are found. When I visit the URL (and manually add the token), I can see all the playlists. 

```
2021-10-18 11:48:49,284 - plugins - INFO - Running applet: 056907c6-3028-11ec-a267-0242ac110004 (plugins.py:251)
2021-10-18 11:48:49,284 - plugins - DEBUG - Running plugin plex v0.1 (plugins.py:158)
2021-10-18 11:48:49,285 - 🎧 plex - INFO - Requesting playlists from endpoint: http://192.168.2.212:32400/playlists/?X-Plex-Token=*********** (up_plex.py:179)
2021-10-18 11:48:49,298 - 🎧 plex - INFO - Found 0 playlists. (up_plex.py:195)
2021-10-18 11:48:49,298 - plugins - DEBUG - Running plugin spotify v0.3 (plugins.py:158)
2021-10-18 11:48:49,299 - 🎧 spotify - INFO - Credentials will be cached in: /config/up_spotify/up_spotify.bz2 (up_spotify.py:104)
2021-10-18 11:48:49,300 - 🎧 spotify - DEBUG - Fetching your Spotify token (up_spotify.py:121)
2021-10-18 11:48:49,559 - 🎧 spotify - DEBUG - Token is valid. (up_spotify.py:152)
2021-10-18 11:48:49,559 - 🎧 spotify - DEBUG - Returning cached token (up_spotify.py:129)
2021-10-18 11:48:49,839 - 🎧 spotify - INFO - Found 36 playlist(s) on Spotify. (up_spotify.py:340)
2021-10-18 11:48:49,839 - plugins - INFO - Applet 056907c6-3028-11ec-a267-0242ac110004 completed successfully in 0:00:00.555649 (plugins.py:296)
2021-10-18 11:48:49,844 - database - INFO - Applet lastrun updated (database.py:377)
```

Any thoughts on what may be going on? Not sure if it matters, but I am using the docker container.

**Comment by XDGFX** [comment]
Ah, I had incorrectly named a dict entry in the new beta plugin, try with the latest commit on the 1.2.0 branch (or the latest 1.2.0 Docker tag)

**Comment by arsaboo** [comment]
Ok...so some progress. So some of the playlists now work. On one of my playlist (from Plex to Spotify), I get this error and then the processing of the playlist stops. 
```
2021-11-10 12:32:00,050 - plugins - ERROR - ekey was not provided (plugins.py:291)
Traceback (most recent call last):
  File "/home/arsaboo/ultrasonics/ultrasonics/plugins.py", line 273, in applet_run
    for item in plugin_run(*get_info(plugin), component="inputs", applet_id=applet_id):
  File "/home/arsaboo/ultrasonics/ultrasonics/plugins.py", line 162, in plugin_run
    response = found_plugins[name].run(
  File "/home/arsaboo/ultrasonics/ultrasonics/official_plugins/up_plex beta.py", line 129, in run
    playlist_dict["songs"].append(plexapi_to_ultrasonics(track))
  File "/home/arsaboo/ultrasonics/ultrasonics/official_plugins/up_plex beta.py", line 78, in plexapi_to_ultrasonics
    track_dict["artists"] = [track.artist().title]
  File "/home/arsaboo/ultrasonics/.venv/lib/python3.8/site-packages/plexapi/audio.py", line 409, in artist
    return self.fetchItem(self.grandparentKey)
  File "/home/arsaboo/ultrasonics/.venv/lib/python3.8/site-packages/plexapi/base.py", line 169, in fetchItem
    raise BadRequest('ekey was not provided')
plexapi.exceptions.BadRequest: ekey was not provided
```
I have to tell you that it is a large playlist (with over 10K tracks).

**Comment by arsaboo** [comment]
So, looks like the process is working. However, the matching is terrible. I have a playlist of over 10K tracks and only 1200 were matched :(

This is not your fault, but how Spotify organizes tracks. Sometimes the tracks are organized in `albums`, sometimes they will organize it as `tracktitle (from albumtitle)` and so on. I like how beets handles this situation by giving an option to manually intervene. Wondering if it would be a better idea to give an option for manual matching like beets does.
