### ISSUE TITLE
Spotify to Plex - New issue

### ISSUE THREAD

**Issue by Drazzilb08** [XDGFX/ultrasonics#42]
New issue running Ultrasonics via docker

```
[31m2022-01-21 02:27:56,300 - plugins - ERROR - 'NoneType' object is not subscriptable (plugins.py:291)[0m

Traceback (most recent call last):
File "/ultrasonics/official_plugins/up_spotify.py", line 393, in playlist_tracks
track_list.append(s.spotify_to_songs_dict(track))
File "/ultrasonics/official_plugins/up_spotify.py", line 419, in spotify_to_songs_dict
artists = [artist["name"] for artist in track["artists"]]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/ultrasonics/plugins.py", line 273, in applet_run
for item in plugin_run(*get_info(plugin), component="inputs", applet_id=applet_id):
File "/ultrasonics/plugins.py", line 162, in plugin_run
response = found_plugins[name].run(
File "/ultrasonics/official_plugins/up_spotify.py", line 568, in run
tracks = s.playlist_tracks(playlist["id"]["spotify"])
File "/ultrasonics/official_plugins/up_spotify.py", line 396, in playlist_tracks
f"Could not convert track {track['id']} to ultrasonics format."
TypeError: 'NoneType' object is not subscriptable
[33m2022-01-21 02:27:56,302 - plugins - WARNING - Applet 51905f78-5706-11ec-b0e3-0242ac170012 failed in 0:00:08.192591 (plugins.py:299)[0m
```

Thanks

**Comment by vindevil** [comment]
It happened to me today when I tried to sync this playlist:
https://open.spotify.com/playlist/3ysRoQDvsA9sGHz5lxYR1W?si=af958064de2247c0

It includes several songs removed by Spotify which display in grey and miss some meta data.

```
70it [00:16,  7.00it/s]2022-01-22 08:30:53,595 - 🎧 spotify - INFO - Converting tracks to ultrasonics format. (up_spotify.py:387)
                                                                                    2022-01-22 08:30:53,598 - 🎧 spotify - DEBUG - Invalid spotify id for song: Ariana Grande - Side to Side Live (One Love Manchester) (up_spotify.py:447)[00:00<?, ?it/s]
Converting tracks in 3ysRoQDvsA9sGHz5lxYR1W:  65%|██████▌   | 149/229 [00:00<00:00, 56546.44it/s]
70it [00:16,  4.23it/s]
2022-01-22 08:30:53,601 - plugins - ERROR - 'NoneType' object is not subscriptable (plugins.py:291)
Traceback (most recent call last):
  File "/ultrasonics/official_plugins/up_spotify.py", line 393, in playlist_tracks
    track_list.append(s.spotify_to_songs_dict(track))
  File "/ultrasonics/official_plugins/up_spotify.py", line 419, in spotify_to_songs_dict
    artists = [artist["name"] for artist in track["artists"]]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ultrasonics/plugins.py", line 273, in applet_run
    for item in plugin_run(*get_info(plugin), component="inputs", applet_id=applet_id):
  File "/ultrasonics/plugins.py", line 162, in plugin_run
    response = found_plugins[name].run(
  File "/ultrasonics/official_plugins/up_spotify.py", line 568, in run
    tracks = s.playlist_tracks(playlist["id"]["spotify"])
  File "/ultrasonics/official_plugins/up_spotify.py", line 396, in playlist_tracks
    f"Could not convert track {track['id']} to ultrasonics format."
TypeError: 'NoneType' object is not subscriptable
2022-01-22 08:30:53,618 - plugins - WARNING - Applet fb19ef4a-7b5b-11ec-bf82-0242ac180002 failed in 0:00:18.200308 (plugins.py:299)
2022-01-22 08:30:53,621 - database - INFO - Applet lastrun updated (database.py:377)
2022-01-22 08:30:53,622 - plugins - DEBUG - Running plugin time trigger v0.2 (plugins.py:158)
2022-01-22 08:30:53,624 - 🎧 time trigger - INFO - Applet fb19ef4a-7b5b-11ec-bf82-0242ac180002 will run in 86261 seconds... (up_time trigger.py:149)
```

**Comment by JDLHiguera** [comment]
Also happened to me, here are the logs:
`ultrasonics  | 2022-01-31 16:48:08,140 - plugins - INFO - Running applet: 0a998c7c-82b5-11ec-a588-0242ac140002 (plugins.py:251)
ultrasonics  | 2022-01-31 16:48:08,151 - plugins - DEBUG - Running plugin spotify v0.5 (plugins.py:158)
ultrasonics  | 2022-01-31 16:48:08,176 - 🎧 spotify - INFO - Credentials will be cached in: /config/up_spotify/up_spotify.bz2 (up_spotify.py:93)
ultrasonics  | 2022-01-31 16:48:08,194 - 🎧 spotify - DEBUG - Fetching your Spotify token (up_spotify.py:110)
ultrasonics  | 2022-01-31 16:48:08,334 - 🎧 spotify - DEBUG - Token is valid. (up_spotify.py:136)
ultrasonics  | 2022-01-31 16:48:08,334 - 🎧 spotify - DEBUG - Returning cached token (up_spotify.py:118)
ultrasonics  | 2022-01-31 16:48:08,835 - 🎧 spotify - INFO - Found 88 playlist(s) on Spotify. (up_spotify.py:331)
ultrasonics  | 2022-01-31 16:48:08,835 - 🎧 spotify - INFO - Building songs_dict for playlists... (up_spotify.py:566)
0it [00:00, ?it/s]2022-01-31 16:48:09,344 - 🎧 spotify - INFO - Converting tracks to ultrasonics format. (up_spotify.py:387)
Converting tracks in 3PkJETgfbriv4LwGnsnsQr:  61%|██████    | 187/308 [00:00<00:00, 266237.22it/s]
0it [00:00, ?it/s]in 3PkJETgfbriv4LwGnsnsQr:   0%|          | 0/308 [00:00<?, ?it/s]
ultrasonics  | 2022-01-31 16:48:09,345 - plugins - ERROR - 'NoneType' object is not subscriptable (plugins.py:291)
ultrasonics  | Traceback (most recent call last):
ultrasonics  |   File "/ultrasonics/official_plugins/up_spotify.py", line 393, in playlist_tracks
ultrasonics  |     track_list.append(s.spotify_to_songs_dict(track))
ultrasonics  |   File "/ultrasonics/official_plugins/up_spotify.py", line 419, in spotify_to_songs_dict
ultrasonics  |     artists = [artist["name"] for artist in track["artists"]]
ultrasonics  | TypeError: 'NoneType' object is not subscriptable
ultrasonics  | 
ultrasonics  | During handling of the above exception, another exception occurred:
ultrasonics  | 
ultrasonics  | Traceback (most recent call last):
ultrasonics  |   File "/ultrasonics/plugins.py", line 273, in applet_run
ultrasonics  |     for item in plugin_run(*get_info(plugin), component="inputs", applet_id=applet_id):
ultrasonics  |   File "/ultrasonics/plugins.py", line 162, in plugin_run
ultrasonics  |     response = found_plugins[name].run(
ultrasonics  |   File "/ultrasonics/official_plugins/up_spotify.py", line 568, in run
ultrasonics  |     tracks = s.playlist_tracks(playlist["id"]["spotify"])
ultrasonics  |   File "/ultrasonics/official_plugins/up_spotify.py", line 396, in playlist_tracks
ultrasonics  |     f"Could not convert track {track['id']} to ultrasonics format."
ultrasonics  | TypeError: 'NoneType' object is not subscriptable
ultrasonics  | 2022-01-31 16:48:09,346 - plugins - WARNING - Applet 0a998c7c-82b5-11ec-a588-0242ac140002 failed in 0:00:01.206083 (plugins.py:299)
ultrasonics  | 2022-01-31 16:48:09,469 - database - INFO - Applet lastrun updated (database.py:377)`

**Comment by JDLHiguera** [comment]
Also happened to me, here are the logs:
```ultrasonics  | 2022-01-31 16:48:08,140 - plugins - INFO - Running applet: 0a998c7c-82b5-11ec-a588-0242ac140002 (plugins.py:251)
ultrasonics  | 2022-01-31 16:48:08,151 - plugins - DEBUG - Running plugin spotify v0.5 (plugins.py:158)
ultrasonics  | 2022-01-31 16:48:08,176 - 🎧 spotify - INFO - Credentials will be cached in: /config/up_spotify/up_spotify.bz2 (up_spotify.py:93)
ultrasonics  | 2022-01-31 16:48:08,194 - 🎧 spotify - DEBUG - Fetching your Spotify token (up_spotify.py:110)
ultrasonics  | 2022-01-31 16:48:08,334 - 🎧 spotify - DEBUG - Token is valid. (up_spotify.py:136)
ultrasonics  | 2022-01-31 16:48:08,334 - 🎧 spotify - DEBUG - Returning cached token (up_spotify.py:118)
ultrasonics  | 2022-01-31 16:48:08,835 - 🎧 spotify - INFO - Found 88 playlist(s) on Spotify. (up_spotify.py:331)
ultrasonics  | 2022-01-31 16:48:08,835 - 🎧 spotify - INFO - Building songs_dict for playlists... (up_spotify.py:566)
0it [00:00, ?it/s]2022-01-31 16:48:09,344 - 🎧 spotify - INFO - Converting tracks to ultrasonics format. (up_spotify.py:387)
Converting tracks in 3PkJETgfbriv4LwGnsnsQr:  61%|██████    | 187/308 [00:00<00:00, 266237.22it/s]
0it [00:00, ?it/s]in 3PkJETgfbriv4LwGnsnsQr:   0%|          | 0/308 [00:00<?, ?it/s]
ultrasonics  | 2022-01-31 16:48:09,345 - plugins - ERROR - 'NoneType' object is not subscriptable (plugins.py:291)
ultrasonics  | Traceback (most recent call last):
ultrasonics  |   File "/ultrasonics/official_plugins/up_spotify.py", line 393, in playlist_tracks
ultrasonics  |     track_list.append(s.spotify_to_songs_dict(track))
ultrasonics  |   File "/ultrasonics/official_plugins/up_spotify.py", line 419, in spotify_to_songs_dict
ultrasonics  |     artists = [artist["name"] for artist in track["artists"]]
ultrasonics  | TypeError: 'NoneType' object is not subscriptable
ultrasonics  | 
ultrasonics  | During handling of the above exception, another exception occurred:
ultrasonics  | 
ultrasonics  | Traceback (most recent call last):
ultrasonics  |   File "/ultrasonics/plugins.py", line 273, in applet_run
ultrasonics  |     for item in plugin_run(*get_info(plugin), component="inputs", applet_id=applet_id):
ultrasonics  |   File "/ultrasonics/plugins.py", line 162, in plugin_run
ultrasonics  |     response = found_plugins[name].run(
ultrasonics  |   File "/ultrasonics/official_plugins/up_spotify.py", line 568, in run
ultrasonics  |     tracks = s.playlist_tracks(playlist["id"]["spotify"])
ultrasonics  |   File "/ultrasonics/official_plugins/up_spotify.py", line 396, in playlist_tracks
ultrasonics  |     f"Could not convert track {track['id']} to ultrasonics format."
ultrasonics  | TypeError: 'NoneType' object is not subscriptable
ultrasonics  | 2022-01-31 16:48:09,346 - plugins - WARNING - Applet 0a998c7c-82b5-11ec-a588-0242ac140002 failed in 0:00:01.206083 (plugins.py:299)
ultrasonics  | 2022-01-31 16:48:09,469 - database - INFO - Applet lastrun updated (database.py:377)```
