### ISSUE TITLE
Entering no fuzzy search ratio for Plex crashes the applet

### ISSUE THREAD

**Issue by SolveSoul** [XDGFX/ultrasonics#47]
When trying to sync from Spotify to Plex the applet crashes when no fuzzy search ratio is set. Of course one should set-up a fuzzy search ratio but it shouldn't be possible to not enter a value or should default to another value when none is set by the user.

See details below:

Image of exception:
<img width="927" alt="Screenshot 2022-04-14 at 14 03 38" src="https://user-images.githubusercontent.com/6033289/163386899-e858223c-3cbc-4762-bd43-d622a374686d.png">

Raw text:
```
2022-04-13 13:42:43,447 - plugins - ERROR - could not convert string to float: '' (plugins.py:291)
Traceback (most recent call last):
  File "/ultrasonics/plugins.py", line 285, in applet_run
    plugin_run(*get_info(plugin), component="outputs",
  File "/ultrasonics/plugins.py", line 162, in plugin_run
    response = found_plugins[name].run(
  File "/ultrasonics/official_plugins/up_plex.py", line 203, in run
    if max(scores) >= float(settings_dict["fuzzy_ratio"]):
ValueError: could not convert string to float: ''
2022-04-13 13:42:43,481 - plugins - WARNING - Applet 85d4ee3a-b0f6-11ec-8802-0242ac120006 failed in 0:01:11.935786 (plugins.py:299)
```

**Comment by Paytah232** [comment]
@XDGFX +1 to this. I have the same issue on a docker install.
![image](https://user-images.githubusercontent.com/44075588/163766463-e51f42aa-5bac-44d0-95e8-84d0b811f839.png)
