### ISSUE TITLE
Can't sync local playlist with Plex

### ISSUE THREAD

**Issue by off112a** [XDGFX/ultrasonics#49]
Hi,

I can't sync local playlist with Plex. I get this error message:

`2022-04-29 11:56:38,122 - plugins - DEBUG - Running plugin local playlists v0.4 (plugins.py:158)
2022-04-29 11:56:38,124 - 🎧 local playlists - INFO - Found 21 playlist(s) in supplied directory. (up_local playlists.py:254)
2022-04-29 11:56:38,124 - 🎧 local playlists - INFO - 21 playlist(s) match supplied filter. (up_local playlists.py:263)
2022-04-29 11:56:38,125 - plugins - ERROR - 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte (plugins.py:291)
Traceback (most recent call last):
File "/ultrasonics/plugins.py", line 273, in applet_run
for item in plugin_run(*get_info(plugin), component="inputs", applet_id=applet_id):
File "/ultrasonics/plugins.py", line 162, in plugin_run
response = found_plugins[name].run(
File "/ultrasonics/official_plugins/up_local playlists.py", line 273, in run
songs = io.open(playlist["path"], "r", encoding="utf8").read().splitlines()
File "/usr/local/lib/python3.8/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
2022-04-29 11:56:38,159 - plugins - WARNING - Applet d339aed0-c786-11ec-b2c4-0242ac1b0002 failed in 0:00:00.073421 (plugins.py:299)
2022-04-29 11:56:38,296 - database - INFO - Applet lastrun updated (database.py:377)`

I can sync from Plex to local playlist without any problems. 

I have tried to remove my local playlist and sync new from Plex and directly afterwards sync from local to Plex. But  I get the same error message.

**Comment by off112a** [comment]
I found out what the problem was. It was some hidden playlist files in the folder. The error disappeared when I removed them.

But now I have a new error message and the playlist won't sync.

`2022-05-02 17:59:13,786 - plugins - INFO - Running applet: d339aed0-c786-11ec-b2c4-0242ac1b0002 (plugins.py:251)
2022-05-02 17:59:13,787 - plugins - DEBUG - Running plugin local playlists v0.4 (plugins.py:158)
2022-05-02 17:59:13,789 - 🎧 local playlists - INFO - Found 1 playlist(s) in supplied directory. (up_local playlists.py:254)
2022-05-02 17:59:13,789 - 🎧 local playlists - INFO - 1 playlist(s) match supplied filter. (up_local playlists.py:263)

Processing playlist: Test:   0%|          | 0/1 [00:00<?, ?it/s]
Processing playlist: Test: 100%|██████████| 1/1 [00:00<00:00, 193.97it/s]
2022-05-02 17:59:13,795 - plugins - DEBUG - Running plugin playlist merger v0.1 (plugins.py:158)
2022-05-02 17:59:13,796 - 🎧 playlist merger - INFO - Using a fuzzy ratio of 90.0 (up_playlist merger.py:73)
2022-05-02 17:59:13,796 - 🎧 playlist merger - INFO - Found 0 duplicate playlist(s) (up_playlist merger.py:90)
2022-05-02 17:59:13,797 - plugins - DEBUG - Running plugin plex v1.0 (plugins.py:158)

Processing playlists:   0%|          | 0/1 [00:00<?, ?it/s]2022-05-02 17:59:13,812 - 🎧 plex - INFO - Processing playlist: Test (up_plex.py:159)

Adding songs:   0%|          | 0/1 [00:00<?, ?it/s]
Adding songs:   0%|          | 0/1 [00:00<?, ?it/s]

Processing playlists:   0%|          | 0/1 [00:00<?, ?it/s]
2022-05-02 17:59:14,147 - plugins - ERROR - could not convert string to float: '' (plugins.py:291)
Traceback (most recent call last):
  File "/ultrasonics/plugins.py", line 285, in applet_run
    plugin_run(*get_info(plugin), component="outputs",
  File "/ultrasonics/plugins.py", line 162, in plugin_run
    response = found_plugins[name].run(
  File "/ultrasonics/official_plugins/up_plex.py", line 203, in run
    if max(scores) >= float(settings_dict["fuzzy_ratio"]):
ValueError: could not convert string to float: ''
2022-05-02 17:59:14,148 - plugins - WARNING - Applet d339aed0-c786-11ec-b2c4-0242ac1b0002 failed in 0:00:00.361715 (plugins.py:299)
2022-05-02 17:59:14,445 - database - INFO - Applet lastrun updated (database.py:377)`
