### ISSUE TITLE
Unable to sync Spotify to Plex

### ISSUE THREAD

**Issue by Jenni32222** [XDGFX/ultrasonics#54]
Used to work, now seems to be broken.

2022-08-06 15:22:27,681 - plugins - ERROR - could not convert string to float: '' (plugins.py:291)

Traceback (most recent call last):

  File "/ultrasonics/plugins.py", line 285, in applet_run

    plugin_run(*get_info(plugin), component="outputs",

  File "/ultrasonics/plugins.py", line 162, in plugin_run

    response = found_plugins[name].run(

  File "/ultrasonics/official_plugins/up_plex.py", line 203, in run

    if max(scores) >= float(settings_dict["fuzzy_ratio"]):

ValueError: could not convert string to float: ''

**Comment by jelly-monster** [comment]
I get the same error.  Let me know if you find a fix.
